apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-flask
  namespace: devops-demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sample-flask
  namespaceSelector:
    matchNames:
      - devops-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
